name: getui
description: A Flutter plugin that allow Flutter to communicate with GTSDK.
version: 0.1.0
author: Bai <equweiyu@hotmail.com>
homepage: https://github.com/hui-z/getui_plugin

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    androidPackage: com.zaihui.getui
    pluginClass: GetuiPlugin